routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => LaravelLocalization::setLocale(),'namespace'=>'Index'], function()
{
    /*Localizer*/
    $locale = App::getLocale();

    View::share('locale',$locale);
    View::share('title','title_'.$locale);
    View::share('short_desc','short_desc_'.$locale);
    View::share('desc','desc_'.$locale);
    View::share('price','price_'.$locale);
    View::share('title_button','title_button_'.$locale);

    Route::get('/','IndexController@index');
    Route::get('call','IndexController@call')->name('call');
    Route::get('auth/login','AuthController@getLogin')->name('authGetLogin');
    Route::post('auth/login','AuthController@postLogin')->name('authPostLogin');
    Route::get('auth/register','AuthController@getRegister')->name('authGetRegister');
    Route::post('auth/register','AuthController@postRegister')->name('authPostRegister');
    Route::get('services','IndexController@service')->name('services');
    Route::get('tests','IndexController@tests')->name('tests');
    Route::get('keyup-search','IndexController@keydownSearch');
    Route::get('keyup-result','IndexController@keydownResult');
    Route::get('search-button','IndexController@searchButton');
    Route::get('faq','IndexController@faq')->name('faq');
    Route::post('profile-question-save','IndexController@profileQuestionSave')->name('profileQuestionSave');
    Route::get('logout','AuthController@logout')->name('logout');
    Route::post('profile-article-save','IndexController@profileArticleSave')->name('profileArticleSave');
    Route::get('reviews','IndexController@reviews');
    Route::get('reasons','IndexController@reasons')->name('reasons');
    Route::get('lor','IndexController@lor')->name('lor');
    Route::get('nevrolog','IndexController@nevrolog')->name('nevrolog');
    Route::post('send-call-application','IndexController@sendCallApplication');
});
Route::group(['prefix' => LaravelLocalization::setLocale(),'namespace'=>'Index','middleware'=>'site'], function()
{
    Route::get('profile','ProfileController@profile')->name('profile');
    Route::post('profile-request-save','ProfileController@profileRequestSave')->name('profile_request_save');
});

Auth::routes();
Route::group(['prefix'=>'system','middleware'=>['auth','admin'],'namespace'=>'System'],function (){
    Route::get('/', 'IndexController@index')->name('main');
    Route::get('/logout', 'IndexController@getSignOut')->name('main');
    Route::resource('carousel', 'CarouselController');
    Route::resource('service', 'ServiceController');
    Route::resource('test-category', 'TestCategoryController');
    Route::resource('test', 'TestController');
    Route::get('faq', 'FaqController@index')->name('faq.index');
    Route::get('faq/create','FaqController@create')->name('faq.create');
    Route::post('faq/store','FaqController@store')->name('faq.save');
    Route::get('faq/{id}/edit','FaqController@edit')->name('faq.edit');
    Route::post('faq/{id}/store','FaqController@update')->name('faq.store');
    Route::post('faq/{id}/delete','FaqController@delete')->name('faq.delete');
    Route::resource('review','ReviewController');
    Route::resource('reasons','ReasonsController');
    Route::resource('lor-content','LorContentController');
    Route::get('application','ApplicationController@index');
    Route::post('/update-form-element/{id}','ApplicationController@updateToArchive');
    Route::post('/delete-form-element/{id}','ApplicationController@destroy');
    Route::get('users','IndexController@users');
    Route::post('delete-form-user/{id}','IndexController@deleteFromUser');
});

app/Models/TestCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TestCategory extends Model
{
    protected $table = 'test_categories';
    protected $guarded =['id'];

    protected $hidden = ['_token','created_at','updated_at'];
}

app/Http/Controllers/System/ApplicationController.php
<?php

namespace App\Http\Controllers\System;

use App\Models\Application;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ApplicationController extends Controller
{
    public function index(Request $request)
    {
        $input =$request->all();
        if(isset($input['is_archive']) && $input['is_archive'] == 1){
            $rows['application'] = Application::where('is_archive',1)->orderBy('id','desc')->get();
        }else{
            $rows['application'] = Application::where('is_archive',0)->orderBy('id','desc')->get();
        }
        return view('system.application.index',compact('rows'));
    }

    public function updateToArchive(Request $request,$id)
    {
        Application::where('id',$id)->update([
           'is_archive'=>1
        ]);
        $result['result'] = 1;
        return $result;
    }

    public function destroy($id)
    {
        $application = Application::find($id);
        $application->delete();
        $result['result'] = 1;
        return $result;
    }
}

app/Http/Controllers/System/CarouselController.php
<?php

namespace App\Http\Controllers\System;

use App\Models\Carousel;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\File;

class CarouselController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rows['carousels'] = Carousel::latest('id','desc')->get();
        return view('system.carousel.index',compact('rows'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('system.carousel.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'title_ru'=>'required',
            'short_desc_ru' =>'required',
            'title_button_ru'=>'required',
            'image'=>'required',
            'type'=>'required'
        ]);
        $input = $request->all();
        if($request->hasFile('image')){
            $image = $request->file('image');
            $imageName = time().'.'.$image->getClientOriginalExtension();
            $image->move(public_path('uploads/carousels'),$imageName);
        }
        $input['image'] = $imageName;
        Carousel::create($input);
        return redirect()->route('carousel.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $rows['carousel'] = Carousel::find($id);
        return view('system.carousel.edit',compact('rows'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title_ru'=>'required',
            'short_desc_ru' =>'required',
            'title_button_ru'=>'required',
            'type'=>'required'
        ]);
        $input = $request->all();
        $carousel = Carousel::find($id);
        if($request->hasFile('image')){
            File::delete('uploads/carousels/'.$carousel['image']);
            $image = $request->file('image');
            $imageName = time().'.'.$image->getClientOriginalExtension();
            $image->move(public_path('uploads/carousels'),$imageName);
            $input['image'] = $imageName;
        }
        $carousel->update($input);
        return redirect()->route('carousel.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $carousel = Carousel::find($id);
        File::delete('uploads/carousels/'.$carousel['image']);
        $carousel->delete();
        $result['result'] = 1;
        return $result;
    }
}

app/Http/Controllers/System/FaqController.php
<?php

namespace App\Http\Controllers\System;

use App\Models\Faq;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FaqController extends Controller
{
    public function index()
    {
        $rows['faqs'] = Faq::orderBy('id','desc')->get();
        return view('system.faq.index',compact('rows'));
    }

    public function edit($id)
    {
        $rows['faq'] = Faq::find($id);
        return view('system.faq.edit',compact('rows'));
    }

    public function create()
    {
        $rows['users'] = User::where('role',0)->select(['id','name'])->get();
        return view('system.faq.create',compact('rows'));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
           'email'=>'required|email',
           'user_id'=>'required',
            'query'=>'required'
        ]);

        $input = $request->all();
        if(isset($input['is_site'])) {
            $input['is_site'] = 1;
        }else{
            $input['is_site'] = 0;
        }
        Faq::create($input);

        return redirect()->route('faq.index');
    }
    public function update(Request $request,$id)
    {
        $this->validate($request,[
            'email'=>'required|email',
            'query'=>'required',
        ]);
        $input = $request->all();
        $input['is_site'] = isset($request['is_site']) ? 1 : 0;
        $faq = Faq::find($id);
        $faq->update($input);
        return redirect()->route('faq.index');
    }

    public function delete($id)
    {
        $faq = Faq::find($id);
        $faq->delete();
        $result['result'] = 1;
        return $result;
    }
}

app/Http/Controllers/System/IndexController.php
<?php

namespace App\Http\Controllers\System;

use App\Models\Application;
use App\Models\Carousel;
use App\Models\Faq;
use App\Models\Post;
use App\Models\Review;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
class IndexController extends Controller
{
    public function index()
    {
        $rows['service'] = Post::where('category_id',1)->count();
        $rows['carousel'] = Carousel::count();
        $rows['reasons'] = Post::where( 'category_id',2)->count();
        $rows['faq_site'] = Faq::where('is_site',1)->count();
        $rows['faq_archive'] = Faq::where('is_site',0)->count();
        $rows['review_site'] = Review::where('is_site',1)->count();
        $rows['review_archive'] = Review::where('is_site',0)->count();
        $rows['application_site'] = Application::where('is_archive',0)->count();
        $rows['application_archive'] = Application::where('is_archive',1)->count();
        return view ('system.index',compact('rows'));
    }

    public function getSignOut() {

        Auth::logout();
        return redirect('/');

    }

    public function users()
    {
        $rows['users'] = User::where('role',0)->orderBy('name','asc')->get();
        return view('system.users.index',compact('rows'));
    }

    public function deleteFromUser($id)
    {
        $user = User::find($id);
        $user->delete();
        $result['result'] = 1;
        return $result;
    }
}

app/Http/Controllers/System/LorContentController.php
<?php

namespace App\Http\Controllers\System;

use App\Models\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LorContentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rows['lor-content'] = Post::where('category_id',3)
            ->orderBy('id','desc')
            ->get();
        return view('system.lor-content.index',compact('rows'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('system.lor-content.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
           'title_ru'=>'required',
           'price_ru'=>'required',
           'sorting'=>'required',
        ]);

        $input = $request->all();
        $input['category_id'] = 3;
        $input['type'] = 1;

        Post::create($input);

        return redirect()->route('lor-content.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $rows['lor-content'] = Post::find($id);
        return view('system.lor-content.edit',compact('rows'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'title_ru'=>'required',
            'price_ru'=>'required',
            'sorting'=>'required',
        ]);
        $lor_content = Post::find($id);
        $input = $request->all();
        $input['category_id'] = 3;
        $input['type'] = 1;

        $lor_content->update($input);

        return redirect()->route('lor-content.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $lor_content = Post::find($id);
        $lor_content->delete();
        $result['result'] = 1;
        return $result;
    }
}

app/Http/Controllers/System/ReviewController.php
<?php

namespace App\Http\Controllers\System;

use App\Models\Review;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ReviewController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rows['reviews'] = Review::orderBy('id','desc')->get();
        return view('system.review.index',compact('rows'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $rows['users'] = User::where('role',0)->select(['id','name'])->get();
        return view('system.review.create',compact('rows'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
           'email'=>'required|email',
           'user_id'=>'required',
            'review'=>'required'
        ]);
        $input = $request->all();

        if(isset($input['is_site'])){
            $input['is_site'] = 1;
        }else{
            $input['is_site'] = 0;
        }

        Review::create($input);

        return redirect()->route('review.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $rows['review'] = Review::find($id);
        return view('system.review.edit',compact('rows'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'email'=>'required',
            'review'=>'required'
        ]);

        $input = $request->all();
        $input['is_site'] = isset($request['is_site']) ? 1 : 0;
        $review = Review::find($id);
        $review->update($input);
        return redirect()->route('review.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $review = Review::find($id);
        $review->delete();
        $result['result'] = 1;
        return $result;
    }
}

resources/views/system/test-category/create.blade.php
@extends('system.layouts.app')
@section('content')
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Категория анализов | Добавление</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="/system">Администрация</a></li>
                <li class="active">Категория анализов</li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-wrapper p-b-10 collapse in">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="white-box">
                                <form action="{{route('test-category.store')}}" method="POST" class="form-horizontal" enctype="multipart/form-data">
                                    {{csrf_field()}}
                                    <div class="form-group">
                                        <label class="col-md-12">Заголовок RU *</label>
                                        <div class="col-md-12">
                                            <input type="text" name="title_ru" class="form-control" value="">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-12">Заголовок KK</label>
                                        <div class="col-md-12">
                                            <input type="text" name="title_kk" class="form-control" value="">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="col-md-12">Заголовок EN</label>
                                        <div class="col-md-12">
                                            <input type="text" name="title_en" class="form-control" value="">
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-primary waves-effect waves-light m-r-10">Сохранить</button>
                                    <button type="button" onclick="window.location.href='{{URL::previous()}}';" class="btn btn-inverse waves-effect waves-light">Отмена</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@push('scripts')
    <script src="/js/jasny-bootstrap.js"></script>
    @if(count($errors))
        @foreach ($errors->all() as $error)
            <script>
                $.toast({
                    heading: '{{trans('app.error_when_filling')}}',
                    text : '{{$error}}',
                    position: 'bottom-right',
                    loaderBg: '#ff6849',
                    icon: 'error',
                    hideAfter: 3500
                });
            </script>
        @endforeach
    @endif
@endpush

resources/views/system/test-category/edit.blade.php
@extends('system.layouts.app')
@section('content')
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Категория анализов | Изменение</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="/system">Администрация</a></li>
                <li class="active">Категория анализов</li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-wrapper p-b-10 collapse in">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="white-box">
                                @if(count($rows['test-category']))
                                    <form action="{{route('test-category.update',$rows['test-category']->id)}}" method="POST" class="form-horizontal" enctype="multipart/form-data">
                                        {{csrf_field()}}
                                        {{method_field('PUT')}}
                                        <div class="form-group">
                                            <label class="col-md-12">Заголовок RU *</label>
                                            <div class="col-md-12">
                                                <input type="text" name="title_ru" class="form-control" value="{{$rows['test-category']->title_ru}}">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-12">Заголовок KK</label>
                                            <div class="col-md-12">
                                                <input type="text" name="title_kk" class="form-control" value="{{$rows['test-category']->title_kk}}">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-12">Заголовок EN</label>
                                            <div class="col-md-12">
                                                <input type="text" name="title_en" class="form-control" value="{{$rows['test-category']->title_en}}">
                                            </div>
                                        </div>
                                        <button type="submit" class="btn btn-primary waves-effect waves-light m-r-10">Сохранить</button>
                                        <button type="button" onclick="window.location.href='{{URL::previous()}}';" class="btn btn-inverse waves-effect waves-light">Отмена</button>
                                    </form>
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@push('scripts')
    <script src="/js/jasny-bootstrap.js"></script>
    @if(count($errors))
        @foreach ($errors->all() as $error)
            <script>
                $.toast({
                    heading: '{{trans('app.error_when_filling')}}',
                    text : '{{$error}}',
                    position: 'bottom-right',
                    loaderBg: '#ff6849',
                    icon: 'error',
                    hideAfter: 3500
                });
            </script>
        @endforeach
    @endif
@endpush

resources/views/system/test-category/index.blade.php
@extends('system.layouts.app')
@section('content')
    <div class="row bg-title">
        <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
            <h4 class="page-title">Категория анализов</h4> </div>
        <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
            <ol class="breadcrumb">
                <li><a href="/system">Администрация</a></li>
                <li class="active">Категория анализов</li>
            </ol>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">Список категория анализов <a href="{{route('test-category.create')}}" class="btn btn-inverse pull-right m-l-20 hidden-xs hidden-sm waves-effect waves-light">Добавить</a></div>
                <div class="panel-wrapper p-b-10 collapse in">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="white-box">
                                <div class="table-responsive">
                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>N</th>
                                            <th>Заголовок</th>
                                            <th class="text-nowrap">Действие</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @if(count($rows['test-category']))
                                            @foreach($rows['test-category'] as $item)
                                                <tr id="item_{{$item->id}}">
                                                    <td>{{$loop->iteration}}</td>
                                                    <td>{{$item->title_ru}}</td>
                                                    <td class="text-nowrap">
                                                        <a href="{{route('test-category.edit',$item->id)}}" data-toggle="tooltip" data-original-title="Изменить"> <i class="fa fa-pencil text-inverse m-r-10"></i> </a>
                                                        <a href="javascript:void(0);" class="delete_form_element" data-id="{{$item->id}}" data-toggle="tooltip" data-original-title="Удалить"> <i class="fa fa-close text-danger"></i> </a>
                                                    </td>
                                                </tr>
                                            @endforeach
                                        @endif
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@push('scripts')
    <script>
        $('.delete_form_element').on('click',function () {
            var item =$(this);
            $.post('/system/test-category/'+$(this).attr('data-id'),{_token : '{{csrf_token()}}',_method :'DELETE'},function (data) {
                if (data.result == 1){
                    item.parent().parent().hide();
                }else{
                    alert('Ошибка при удалении');
                }
            });
        });
    </script>
@endpush